[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E222D"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false